### ISSUE TITLE
Segmentation Fault of getRoot function in python

### ISSUE THREAD

**Issue by yxuan0329** [yxuan0329/R-tree-Search-Engine#5]
Briefly describe the data structure I've designed:
- Point (longitude in double, latitude in double) 
- Rect (Point at lower-left, Point at upper-right): a rectangle will be constructed by two points
- Node (Rect, vector<Node *> of its children): a node includes a rectangle itself and a list of children it covers

The tree will have one Node with an empty Rect when initialize.

I was adding insert functions for the Rtree library in #4 , and I've checked the correctness of R-tree by inserting three rect in main.cpp. To check the relationship of each node, I used getRoot() and getChildren() in cpp. The result of the tree structure goes like this: 

Node (the rect of itself) [children inside this rect]

```
Node0 (null rect) [Node(r1), Node(r2)]
                     /           \
                    /             \
         Node(r1) [r3]           Node (r2)
                 / 
                /
          Node(r3)  
```

I'm sure that the code in the main.cpp works well. However, in test_Rtree.py, it turns out that there is a segmentation fault at line 27 if I call Rtree.getRoot(). 
@yungyuc do you have any suggestions?

**Comment by yungyuc** [comment]
Have you tried to run the process in a debugger (gdb/lldb) to see what is the call stack when the segfault happens?

**Comment by tigercosmos** [comment]
sounds like you are trying to access a `nullptr`. 

what I will do:
- build the `.so` with `-g`
- run `gdb python3 `
- now you are in gdb, run `r test_Rtree.py`
- there is a segfault, you will see the call stack

try to learn some gdb commands, which will help you to figure out the issue.

**Comment by tigercosmos** [comment]
@yxuan0329  how's going

**Comment by yxuan0329** [comment]
Hi @yungyuc  @tigercosmos , 

Sorry for the late reply. I tried gdb and pdb and spent a little time learning the commands.
I guess the reason was that I tried to print the memory address in Python after the object was deleted in C++. 
To solve it, I added `return_value_policy::reference` in pybind and soon found the seg fault was solved.

Thank you for helping me to deal with this issue!
